### ISSUE TITLE
Layout of the course to cater for Pangeo & OpenEO exercises

### ISSUE THREAD

**Issue by annefou** [EO-College/cubes-and-clouds#49]
This issue is intended to facilitate discussion on how to structure the course for attendees, as it will include both Pangeo and OpenEO exercises.

A few questions to kick off the discussion:

1. Should we split the course into three parts:
     - A general introduction to cubes and clouds, providing an overview of the concepts, technologies, and available platforms?
     - An OpenEO track for hands-on exercises?
     - A Pangeo track for hands-on exercises?
2. Should we ask attendees to choose a specific track to follow? (This might be challenging for those who are unfamiliar with OpenEO and Pangeo.)

3. Should we offer a certificate to attendees who complete one track?

**Comment by clausmichele** [comment]
I would like to add an alternative to the discussion.

As mentioned previously by Robert (@x4ecro), if we modify the current course structure, it could cause some troubles with users that are doing the course and also for the ones that already got the certificate. Additionally, it would be a lot of work on the EO College side to restructure and test it.

The easiest way to incorporate the new content, in my opinion, would consist in creating a new "Cubes & Clouds - Pangeo Extension" course, which would remain separate.

- Would this new course be a copy of the other one but with different content for the exercises?
- Should it only include the new content?
- Should the user need or not to complete the original Cubes & Clouds course?

**Comment by clausmichele** [comment]
Another possibility that came up during the last project meeting is the following:

- Integrate the new content in the current course (we need to understand how to present the two types of exercises, openEO and Pangeo). This would allow us to integrate lecture 2.4, which wasn't added in the course.
- Deprecate/Hide the current Cubes & Clouds, allowing the current users to see it in their account but no more possible to start it for new users.
- Release the version 2.0 of the course, explaining the additions.
- Modify the certificate, mentioning that it refers to version 2.0

On our side, this approach would simplify much how we can integrate the new content Otherwise, we would need to manage two courses.

Feedbacks are welcome!

**Comment by clausmichele** [comment]
During the mid-term meeting, we decided that the course content will be integrated in the original course on EO College. New lectures can be added without taking the course offline. We will notify the users who already subscribed to the course about the changes. The users who already completed the course will be notified but won’t be required to complete the new lectures to get the certificate they already obtained.
